### PR TITLE
fix: update formula for qlik-cli v2.20.4 release

### PR DESCRIPTION
**Pull request by wennmo**
The homebrew formula for release v2.20.4 was not updated properly for the last release, and the binaries were not added to the repo.

### CODE REVIEW

**Comment by colssonqlik** [comment]
I get 404 when trying to curl these links.
Maybe I'm doing something wrong?

**Comment by wennmo** [comment]
> I get 404 when trying to curl these links. Maybe I'm doing something wrong?

It's because the links point to the master branch, where the binaries are missing. They are part of this PR.

**Comment by colssonqlik** [comment]
> > I get 404 when trying to curl these links. Maybe I'm doing something wrong?
> 
> It's because the links point to the master branch, where the binaries are missing. They are part of this PR.

Thanks for the explanation 😸 

(I should have understood that)

**Review by colssonqlik — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
